import{promises as fs}from'node:fs';import path from'node:path';
const root=process.cwd(),out=path.join(root,'dist'),content=path.join(root,'content');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const states={seed:'种子',budding:'萌芽',evergreen:'常青','种子':'种子','萌芽':'萌芽','常青':'常青'};
function parse(src){const m=src.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);if(!m)return{data:{},body:src};const data={};for(const line of m[1].split(/\r?\n/)){const x=line.match(/^([\w-]+):\s*(.*)$/);if(!x)continue;let v=x[2].trim();if(/^\[.*\]$/.test(v))v=v.slice(1,-1).split(',').map(i=>i.trim().replace(/^['"]|['"]$/g,''));else if(/^(true|false)$/i.test(v))v=v.toLowerCase()==='true';else v=v.replace(/^['"]|['"]$/g,'');data[x[1]]=v}return{data,body:m[2]}}
function inline(text,map){return esc(text).replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g,(_,target,label)=>{const slug=map.get(target.trim());return slug?`<a href="../notes/${slug}.html">${esc(label||target)}</a>`:esc(label||target)}).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>')}
function md(body,map){let html='',list=false;const close=()=>{if(list){html+='</ul>';list=false}};for(const raw of body.split(/\r?\n/)){const line=raw.trim();if(!line){close();continue}if(/^### /.test(line)){close();html+=`<h3>${inline(line.slice(4),map)}</h3>`}else if(/^## /.test(line)){close();html+=`<h2>${inline(line.slice(3),map)}</h2>`}else if(/^# /.test(line)){close();html+=`<h2>${inline(line.slice(2),map)}</h2>`}else if(/^- /.test(line)){if(!list){html+='<ul>';list=true}html+=`<li>${inline(line.slice(2),map)}</li>`}else if(/^> /.test(line)){close();html+=`<blockquote>${inline(line.slice(2),map)}</blockquote>`}else{close();html+=`<p>${inline(line,map)}</p>`}}close();return html}
const files=(await fs.readdir(content)).filter(n=>n.endsWith('.md')),all=[];for(const file of files){const p=parse(await fs.readFile(path.join(content,file),'utf8'));all.push({file,slug:p.data.slug||path.basename(file,'.md'),...p})}
const notes=all.filter(n=>n.data.publish===true&&n.data.private!==true&&n.data.draft!==true),titleMap=new Map(notes.map(n=>[n.data.title,n.slug]));
for(const n of notes){n.links=[...n.body.matchAll(/\[\[([^\]|]+)/g)].map(m=>m[1].trim()).filter(t=>titleMap.has(t));n.backlinks=notes.filter(o=>o!==n&&[...o.body.matchAll(/\[\[([^\]|]+)/g)].some(m=>m[1].trim()===n.data.title))}
await fs.rm(out,{recursive:true,force:true});await fs.mkdir(path.join(out,'notes'),{recursive:true});
let home=await fs.readFile(path.join(root,'index.html'),'utf8'),script=await fs.readFile(path.join(root,'script.js'),'utf8'),styles=await fs.readFile(path.join(root,'styles.css'),'utf8');
const meta=notes.map(n=>({slug:n.slug,category:n.data.category||n.data.area||'知识',state:states[n.data.status]||'萌芽',date:n.data.updated||'',title:n.data.title,summary:n.data.summary||'',tags:Array.isArray(n.data.tags)?n.data.tags:[],links:n.links.length+n.backlinks.length}));
script=script.replace(/const notes = \[[\s\S]*?\];\r?\nconst grid/,`const notes = ${JSON.stringify(meta)};\nconst grid`).replace('<article class="note-card">','<a class="note-card" href="notes/${n.slug}.html">').replace('</div></article>`).join','</div></a>`).join');home=home.replace('href="#garden">浏览全部知识节点','href="garden.html">浏览全部知识节点');
styles+=`.note-card{text-decoration:none;color:inherit}.article-shell{max-width:820px;margin:0 auto;padding:80px 28px 120px}.article-nav{display:flex;justify-content:space-between;align-items:center;margin-bottom:72px}.article-nav a{color:var(--green);text-decoration:none;font-size:13px}.article-header h1{font-family:var(--serif);font-size:48px;line-height:1.3;margin:18px 0}.article-summary{font-size:18px!important;color:var(--muted);line-height:1.8}.article-body{margin-top:55px;font-size:16px;line-height:2;color:#334139}.article-body h2{font-family:var(--serif);font-size:28px;margin-top:48px}.article-body h3{font-family:var(--serif);font-size:21px;margin-top:35px}.article-body a{color:var(--green);text-decoration-color:var(--lime);text-decoration-thickness:3px}.article-body blockquote{border-left:3px solid var(--lime);margin:30px 0;padding:4px 22px;color:var(--muted)}.article-body code{background:#e8ebe2;padding:2px 5px}.connections{margin-top:65px;border-top:1px solid var(--line);padding-top:28px}.connections a{display:inline-block;margin:5px 8px 5px 0;padding:8px 12px;background:#e9ede3;color:var(--green);text-decoration:none;font-size:12px}.garden-page{max-width:1184px;margin:auto;padding:70px 28px 120px}.garden-page h1{font-family:var(--serif);font-size:48px}.garden-page .note-grid{margin-top:40px}@media(max-width:600px){.article-header h1,.garden-page h1{font-size:36px}.article-shell{padding-top:38px}}`;
await Promise.all([fs.writeFile(path.join(out,'index.html'),home),fs.writeFile(path.join(out,'script.js'),script),fs.writeFile(path.join(out,'styles.css'),styles),fs.writeFile(path.join(out,'notes.json'),JSON.stringify(meta,null,2))]);
const head=t=>`<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(t)} · Songspace</title><link rel="stylesheet" href="../styles.css"></head><body>`;
for(const n of notes){const related=[...n.backlinks.map(x=>({slug:x.slug,title:x.data.title})),...n.links.map(title=>({slug:titleMap.get(title),title}))];const html=`${head(n.data.title)}<main class="article-shell"><nav class="article-nav"><a href="../index.html">← Songspace</a><a href="../garden.html">知识花园</a></nav><header class="article-header"><p class="eyebrow">${esc(n.data.category||n.data.area||'知识')} · ${esc(states[n.data.status]||'萌芽')}</p><h1>${esc(n.data.title)}</h1><p class="article-summary">${esc(n.data.summary||'')}</p><div class="tags">${(n.data.tags||[]).map(t=>`<span># ${esc(t)}</span>`).join('')}</div></header><article class="article-body">${md(n.body,titleMap)}</article><aside class="connections"><p class="eyebrow">CONNECTIONS · ${related.length}</p>${related.length?related.map(x=>`<a href="${x.slug}.html">${esc(x.title)} →</a>`).join(''):'<p>这篇笔记正在等待新的连接。</p>'}</aside></main></body></html>`;await fs.writeFile(path.join(out,'notes',`${n.slug}.html`),html)}
const cards=meta.map(n=>`<a class="note-card" href="notes/${n.slug}.html"><div class="note-meta"><span class="state">${esc(n.state)}</span><span>${esc(n.date)}</span></div><h3>${esc(n.title)}</h3><p>${esc(n.summary)}</p><div class="tags">${n.tags.map(t=>`<span># ${esc(t)}</span>`).join('')}</div><div class="note-footer"><span>${esc(n.category)}</span><span>↗ ${n.links} 个连接</span></div></a>`).join('');
await fs.writeFile(path.join(out,'garden.html'),`${head('知识花园').replace('../styles.css','styles.css')}<main class="garden-page"><nav class="article-nav"><a href="index.html">← Songspace</a><span>由 Obsidian 驱动</span></nav><p class="eyebrow">DIGITAL GARDEN · ${notes.length} NODES</p><h1>所有公开知识节点</h1><p class="hero-copy">只有明确标记为 publish 的成熟内容，才会出现在这里。</p><div class="note-grid">${cards}</div></main></body></html>`);console.log(`Built ${notes.length} public notes from ${all.length} Markdown files. Private/draft notes excluded: ${all.length-notes.length}.`);
