const notes = [
  {slug:'growth-knowledge-system',category:'知识',state:'常青',date:'2026.07.16',title:'如何建立一个真正会生长的知识系统',summary:'从收集信息转向建立连接：MOC、渐进式总结与输出驱动输入的实践。',tags:['知识管理','Obsidian'],links:2},
  {slug:'prompt-context-engineering',category:'AI',state:'萌芽',date:'2026.07.12',title:'Prompt 不是咒语，而是上下文工程',summary:'稳定的 AI 输出来自任务环境设计，而不是寻找一句完美指令。',tags:['Prompt','AI 工作流'],links:2},
  {slug:'one-person-product',category:'商业',state:'种子',date:'2026.07.08',title:'一人公司：从技能到最小可售卖产品',summary:'把模糊能力封装成清晰结果，一次小规模商业验证的行动清单。',tags:['商业实验','产品化'],links:0},
  {slug:'deep-reading-loop',category:'英语',state:'常青',date:'2026.07.03',title:'深度阅读：从查单词到复述作者逻辑',summary:'将外刊阅读转化为表达能力的四步循环与复盘模板。',tags:['深度阅读','方法论'],links:0}
];
const grid=document.querySelector('#noteGrid'),search=document.querySelector('#searchInput'),filters=document.querySelector('#filters');let active='all';
function render(){const q=search.value.trim().toLowerCase();const list=notes.filter(n=>(active==='all'||n.category===active)&&[n.title,n.summary,n.category,...n.tags].join(' ').toLowerCase().includes(q));document.querySelector('#noteCount').textContent=`${list.length} 个公开节点 · 由 Obsidian 自动筛选`;grid.innerHTML=list.length?list.map(n=>`<article class="note-card"><div class="note-meta"><span class="state">${n.state}</span><span>${n.date}</span></div><h3>${n.title}</h3><p>${n.summary}</p><div class="tags">${n.tags.map(t=>`<span># ${t}</span>`).join('')}</div><div class="note-footer"><span>${n.category}</span><span>↗ ${n.links} 个连接</span></div></article>`).join(''):'<p class="empty">没有找到匹配的公开知识节点。</p>'}
search.addEventListener('input',render);filters.addEventListener('click',e=>{if(!e.target.matches('button'))return;active=e.target.dataset.filter;filters.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===e.target));render()});render();

const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));
const sections=[...document.querySelectorAll('main section[id]')],navLinks=[...document.querySelectorAll('.main-nav a')];const navObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${entry.target.id}`))}}),{rootMargin:'-35% 0px -55%'});sections.forEach(s=>navObserver.observe(s));

const dialog=document.querySelector('#privateDialog');document.querySelector('#privateButton').addEventListener('click',()=>dialog.showModal());dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
const themeButton=document.querySelector('#themeButton');if(localStorage.getItem('songspace-theme')==='night')document.body.classList.add('night');themeButton.addEventListener('click',()=>{document.body.classList.toggle('night');localStorage.setItem('songspace-theme',document.body.classList.contains('night')?'night':'day')});
const toast=document.querySelector('#toast');let toastTimer;function notify(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2200)}
document.querySelector('[data-action="focus"]').addEventListener('click',()=>document.querySelector('#knowledge').scrollIntoView());document.querySelector('[data-action="reading"]').addEventListener('click',()=>notify('精读资料入口已准备，下一步接入真实素材库。'));

const graphNodes=[{id:'moc',label:'知识系统',x:375,y:210,r:26,c:'#d5ed72'},{id:'obsidian',label:'Obsidian',x:240,y:125,r:18,c:'#d5ed72'},{id:'context',label:'上下文工程',x:520,y:135,r:20,c:'#72b7df'},{id:'agent',label:'AI Agent',x:625,y:225,r:16,c:'#72b7df'},{id:'reading',label:'深度阅读',x:230,y:305,r:19,c:'#e9a872'},{id:'output',label:'语言输出',x:100,y:250,r:14,c:'#e9a872'},{id:'product',label:'产品化',x:500,y:315,r:18,c:'#bb8dd2'},{id:'experiment',label:'商业实验',x:650,y:350,r:15,c:'#bb8dd2'},{id:'attention',label:'注意力',x:110,y:105,r:14,c:'#d5ed72'}];
const graphEdges=[['moc','obsidian'],['moc','context'],['moc','reading'],['moc','product'],['obsidian','attention'],['context','agent'],['context','product'],['reading','output'],['product','experiment'],['attention','reading']];
const svg=document.querySelector('#graphSvg'),ns='http://www.w3.org/2000/svg';function drawGraph(){svg.innerHTML='';graphEdges.forEach(([a,b])=>{const n1=graphNodes.find(n=>n.id===a),n2=graphNodes.find(n=>n.id===b),line=document.createElementNS(ns,'line');line.setAttribute('x1',n1.x);line.setAttribute('y1',n1.y);line.setAttribute('x2',n2.x);line.setAttribute('y2',n2.y);line.setAttribute('class','graph-edge');svg.appendChild(line)});graphNodes.forEach(n=>{const g=document.createElementNS(ns,'g');g.setAttribute('class','graph-node');g.setAttribute('tabindex','0');const circle=document.createElementNS(ns,'circle');circle.setAttribute('cx',n.x);circle.setAttribute('cy',n.y);circle.setAttribute('r',n.r);circle.setAttribute('fill',`${n.c}22`);circle.setAttribute('stroke',n.c);const text=document.createElementNS(ns,'text');text.setAttribute('x',n.x);text.setAttribute('y',n.y+n.r+17);text.setAttribute('text-anchor','middle');text.textContent=n.label;g.append(circle,text);g.addEventListener('click',()=>{search.value=n.label;document.querySelector('#knowledge .notes-head').scrollIntoView({behavior:'smooth'});search.dispatchEvent(new Event('input'))});svg.appendChild(g)})}drawGraph();document.querySelector('#graphReset').addEventListener('click',()=>{search.value='';active='all';filters.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i===0));render();drawGraph()});

const heat=[0,1,2,3,1,4,2,0,3,2,4,4,1,2,3,0,2,4,3,1,0,2,2,4,3,3,1,0,4,2,3,4,1,2,0,3,4,4,2,1,3,4,2,3,1,4,0,2,4,3,2,4,3,0,2,4];document.querySelector('#habitCalendar').innerHTML=heat.map(level=>`<i class="l${level}" title="学习强度 ${level}/4"></i>`).join('');
document.querySelectorAll('[data-output]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-output]').forEach(b=>b.classList.toggle('active',b===button));document.querySelector('#outputContent').innerHTML=button.dataset.output==='writing'?`<div class="diff-block"><p><del>People is easily distracted by informations.</del></p><p><ins>People are easily distracted by a constant stream of information.</ins></p></div><div class="score-row"><span>语法 <b>7.0</b></span><span>词汇 <b>6.5</b></span><span>连贯 <b>7.0</b></span><span>自然度 <b>6.5</b></span></div>`:`<div class="diff-block"><p><b>本周话题：</b>Describe a skill you learned recently</p><p>录音 02:14 · 语速 128 WPM · 停顿 7 次</p></div><div class="score-row"><span>流利度 <b>6.5</b></span><span>发音 <b>7.0</b></span><span>词汇 <b>6.5</b></span><span>语法 <b>6.5</b></span></div>`}));

document.querySelector('#promptSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.prompt-item').forEach(item=>item.hidden=!item.dataset.search.toLowerCase().includes(q)&&!item.textContent.toLowerCase().includes(q))});document.querySelectorAll('.copy-prompt').forEach(button=>button.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(button.dataset.copy);button.textContent='已复制';notify('Prompt 已复制到剪贴板');setTimeout(()=>button.textContent='复制',1500)}catch{notify('浏览器未允许复制，请手动选择。')}}));

const growthData={fitness:`<div class="body-metrics"><article><small>CURRENT WEIGHT</small><strong>68.4 <span>kg</span></strong><em>↓ 3.8 kg / 90 days</em></article><article><small>BODY FAT</small><strong>19.6 <span>%</span></strong><em>↓ 2.1%</em></article><article><small>WAIST</small><strong>78.2 <span>cm</span></strong><em>↓ 4.5 cm</em></article><article><small>TRAINING</small><strong>32 <span>sessions</span></strong><em>88% 完成率</em></article></div>`,skincare:`<div class="body-metrics"><article><small>ROUTINE STREAK</small><strong>28 <span>days</span></strong><em>早晚基础护理</em></article><article><small>SKIN STATUS</small><strong>7.6 <span>/ 10</span></strong><em>较上周期 +0.8</em></article><article><small>PRODUCTS</small><strong>08 <span>active</span></strong><em>2 件待观察</em></article><article><small>NEXT PHOTO</small><strong>06 <span>days</span></strong><em>同光线对比</em></article></div>`,posture:`<div class="body-metrics"><article><small>30-DAY PLAN</small><strong>21 <span>/ 30</span></strong><em>圆肩改善计划</em></article><article><small>MOBILITY</small><strong>14 <span>min/day</span></strong><em>本周平均</em></article><article><small>CHECK-INS</small><strong>03 <span>sets</span></strong><em>正侧背对比</em></article><article><small>PAIN SCORE</small><strong>1.8 <span>/ 10</span></strong><em>↓ 1.2</em></article></div>`,career:`<div class="body-metrics"><article><small>ACTIVE PROJECTS</small><strong>03</strong><em>1 个关键项目</em></article><article><small>SKILL HOURS</small><strong>42 <span>h</span></strong><em>本季度</em></article><article><small>RETROSPECTIVES</small><strong>08</strong><em>KPT 已归档</em></article><article><small>NEXT REVIEW</small><strong>12 <span>days</span></strong><em>月度复盘</em></article></div>`};
document.querySelectorAll('[data-growth]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-growth]').forEach(b=>b.classList.toggle('active',b===button));const metrics=document.querySelector('.body-metrics');metrics.outerHTML=growthData[button.dataset.growth];notify(`已切换到${button.textContent}视图`)}));
document.querySelector('#fitnessForm').addEventListener('submit',e=>{e.preventDefault();if(!document.querySelector('#privacyToggle').checked){notify('请先开启本地隐私保护');return}const data=Object.fromEntries(new FormData(e.target));const logs=JSON.parse(localStorage.getItem('songspace-fitness')||'[]');logs.push({...data,date:new Date().toISOString()});localStorage.setItem('songspace-fitness',JSON.stringify(logs));document.querySelector('#saveMessage').textContent=`已安全保存在本地 · 共 ${logs.length} 条记录`;e.target.reset()});
document.querySelector('#privacyToggle').addEventListener('change',e=>{e.target.closest('.switch').querySelector('b').textContent=e.target.checked?'已保护':'已暂停';notify(e.target.checked?'本地隐私记录已开启':'记录功能已暂停')});
